<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-1SSOFLA" failures="1" tests="32" name="Test Execution using testNG" time="737.568" errors="0" timestamp="2024-02-21T20:05:59 IST">
  <testcase classname="Tests.QKART_Tests" name="TestCase01" time="12.036"/>
  <testcase classname="Tests.QKART_Tests" name="TestCase01" time="10.014"/>
  <testcase classname="Tests.QKART_Tests" name="TestCase01" time="8.152"/>
  <testcase classname="Tests.QKART_Tests" name="TestCase02" time="11.559"/>
  <testcase classname="Tests.QKART_Tests" name="TestCase02" time="11.113"/>
  <testcase classname="Tests.QKART_Tests" name="TestCase02" time="10.307"/>
  <testcase classname="Tests.QKART_Tests" name="TestCase03" time="7.319"/>
  <testcase classname="Tests.QKART_Tests" name="TestCase03" time="7.321"/>
  <testcase classname="Tests.QKART_Tests" name="TestCase03" time="7.996"/>
  <testcase classname="Tests.QKART_Tests" name="TestCase04" time="10.718"/>
  <testcase classname="Tests.QKART_Tests" name="TestCase04" time="10.241"/>
  <testcase classname="Tests.QKART_Tests" name="TestCase04" time="10.563"/>
  <testcase classname="Tests.QKART_Tests" name="TestCase05" time="29.06"/>
  <testcase classname="Tests.QKART_Tests" name="TestCase05" time="23.928"/>
  <testcase classname="Tests.QKART_Tests" name="TestCase05" time="26.647"/>
  <testcase classname="Tests.QKART_Tests" name="TestCase06" time="29.68"/>
  <testcase classname="Tests.QKART_Tests" name="TestCase06" time="29.743"/>
  <testcase classname="Tests.QKART_Tests" name="TestCase06" time="30.866"/>
  <testcase classname="Tests.QKART_Tests" name="TestCase07" time="19.771"/>
  <testcase classname="Tests.QKART_Tests" name="TestCase07" time="19.856"/>
  <testcase classname="Tests.QKART_Tests" name="TestCase07" time="21.754"/>
  <testcase classname="Tests.QKART_Tests" name="TestCase08" time="111.686"/>
  <testcase classname="Tests.QKART_Tests" name="TestCase08" time="40.142">
    <failure type="java.lang.AssertionError" message="Insufficient balance message not shown expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Insufficient balance message not shown expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at Tests.QKART_Tests.TestCase08(QKART_Tests.java:416)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TestCase08 -->
  <testcase classname="Tests.QKART_Tests" name="TestCase08" time="110.961"/>
  <testcase classname="Tests.QKART_Tests" name="TestCase10" time="9.557"/>
  <testcase classname="Tests.QKART_Tests" name="TestCase09" time="14.319"/>
  <testcase classname="Tests.QKART_Tests" name="TestCase11" time="2.412"/>
  <testcase classname="Tests.QKART_Tests" name="TestCase11" time="2.91"/>
  <testcase classname="Tests.QKART_Tests" name="TestCase11" time="2.88"/>
  <testcase classname="Tests.QKART_Tests" name="TestCase12" time="23.562"/>
  <testcase classname="Tests.QKART_Tests" name="TestCase12" time="25.349"/>
  <testcase classname="Tests.QKART_Tests" name="TestCase12" time="25.582"/>
</testsuite> <!-- Test Execution using testNG -->
